"""Add like_count and dislike_count to Artwork

Revision ID: 4bf7f0f5f054
Revises: bd509d042f09
Create Date: 2024-12-18 16:36:00.683790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf7f0f5f054'
down_revision = 'bd509d042f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dislike_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_column('dislike_count')
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###
